# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pipeline_v2_pb2 as pipeline__v2__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/pipelinev2.MasterControl/RegisterWorker',
                request_serializer=pipeline__v2__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=pipeline__v2__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.GetNextWorker = channel.unary_unary(
                '/pipelinev2.MasterControl/GetNextWorker',
                request_serializer=pipeline__v2__pb2.NextWorkerRequest.SerializeToString,
                response_deserializer=pipeline__v2__pb2.NextWorkerResponse.FromString,
                _registered_method=True)
        self.GetPeerAddress = channel.unary_unary(
                '/pipelinev2.MasterControl/GetPeerAddress',
                request_serializer=pipeline__v2__pb2.PeerAddressRequest.SerializeToString,
                response_deserializer=pipeline__v2__pb2.PeerAddressResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/pipelinev2.MasterControl/SubmitTask',
                request_serializer=pipeline__v2__pb2.TaskSubmitRequest.SerializeToString,
                response_deserializer=pipeline__v2__pb2.TaskSubmitResponse.FromString,
                _registered_method=True)
        self.ReportRequestFinished = channel.unary_unary(
                '/pipelinev2.MasterControl/ReportRequestFinished',
                request_serializer=pipeline__v2__pb2.RequestFinishedReport.SerializeToString,
                response_deserializer=pipeline__v2__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportPipelineComplete = channel.unary_unary(
                '/pipelinev2.MasterControl/ReportPipelineComplete',
                request_serializer=pipeline__v2__pb2.PipelineCompleteReport.SerializeToString,
                response_deserializer=pipeline__v2__pb2.Ack.FromString,
                _registered_method=True)


class MasterControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRequestFinished(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportPipelineComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=pipeline__v2__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=pipeline__v2__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'GetNextWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextWorker,
                    request_deserializer=pipeline__v2__pb2.NextWorkerRequest.FromString,
                    response_serializer=pipeline__v2__pb2.NextWorkerResponse.SerializeToString,
            ),
            'GetPeerAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerAddress,
                    request_deserializer=pipeline__v2__pb2.PeerAddressRequest.FromString,
                    response_serializer=pipeline__v2__pb2.PeerAddressResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=pipeline__v2__pb2.TaskSubmitRequest.FromString,
                    response_serializer=pipeline__v2__pb2.TaskSubmitResponse.SerializeToString,
            ),
            'ReportRequestFinished': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRequestFinished,
                    request_deserializer=pipeline__v2__pb2.RequestFinishedReport.FromString,
                    response_serializer=pipeline__v2__pb2.Ack.SerializeToString,
            ),
            'ReportPipelineComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportPipelineComplete,
                    request_deserializer=pipeline__v2__pb2.PipelineCompleteReport.FromString,
                    response_serializer=pipeline__v2__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipelinev2.MasterControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipelinev2.MasterControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.MasterControl/RegisterWorker',
            pipeline__v2__pb2.RegisterWorkerRequest.SerializeToString,
            pipeline__v2__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.MasterControl/GetNextWorker',
            pipeline__v2__pb2.NextWorkerRequest.SerializeToString,
            pipeline__v2__pb2.NextWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.MasterControl/GetPeerAddress',
            pipeline__v2__pb2.PeerAddressRequest.SerializeToString,
            pipeline__v2__pb2.PeerAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.MasterControl/SubmitTask',
            pipeline__v2__pb2.TaskSubmitRequest.SerializeToString,
            pipeline__v2__pb2.TaskSubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRequestFinished(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.MasterControl/ReportRequestFinished',
            pipeline__v2__pb2.RequestFinishedReport.SerializeToString,
            pipeline__v2__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportPipelineComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.MasterControl/ReportPipelineComplete',
            pipeline__v2__pb2.PipelineCompleteReport.SerializeToString,
            pipeline__v2__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataPlaneStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFrame = channel.unary_unary(
                '/pipelinev2.DataPlane/SendFrame',
                request_serializer=pipeline__v2__pb2.Frame.SerializeToString,
                response_deserializer=pipeline__v2__pb2.Ack.FromString,
                _registered_method=True)
        self.NotifyPipelineEnd = channel.unary_unary(
                '/pipelinev2.DataPlane/NotifyPipelineEnd',
                request_serializer=pipeline__v2__pb2.PipelineEndNotification.SerializeToString,
                response_deserializer=pipeline__v2__pb2.Ack.FromString,
                _registered_method=True)


class DataPlaneServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyPipelineEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFrame,
                    request_deserializer=pipeline__v2__pb2.Frame.FromString,
                    response_serializer=pipeline__v2__pb2.Ack.SerializeToString,
            ),
            'NotifyPipelineEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyPipelineEnd,
                    request_deserializer=pipeline__v2__pb2.PipelineEndNotification.FromString,
                    response_serializer=pipeline__v2__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipelinev2.DataPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipelinev2.DataPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataPlane(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.DataPlane/SendFrame',
            pipeline__v2__pb2.Frame.SerializeToString,
            pipeline__v2__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyPipelineEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelinev2.DataPlane/NotifyPipelineEnd',
            pipeline__v2__pb2.PipelineEndNotification.SerializeToString,
            pipeline__v2__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
